create table public.todos (
    id bigint generated by default as identity,
    user_id uuid not null,
    task text null,
    is_complete boolean null default false,
    created_at timestamp with time zone not null default timezone ('utc'::text, now()),
    constraint todos_pkey primary key (id),
    constraint todos_user_id_fkey foreign key (user_id) references user_profiles (id) on delete cascade,
    constraint todos_task_check check ((char_length(task) > 3))
  ) tablespace pg_default;

alter table todos enable row level security;
create policy "Individuals can create todos." on todos for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own todos. " on todos for
    select using (auth.uid() = user_id);
create policy "Individuals can update their own todos." on todos for
    update using (auth.uid() = user_id);
create policy "Individuals can delete their own todos." on todos for
    delete using (auth.uid() = user_id);
